version: '3'

services:
  superMarketAPI:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      "8080:8080"
    deploy:
      mode: replicated
      replicas: 1